# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr:
- none

pool:
  vmImage: 'windows-latest'

variables:
- group: 'fantasy-soccer-provisioning-script-VG'
- group: 'fantasy-soccer-service-principal'
- name: resourceGroup
  value: rg-$(ProjectName)-$(Environment)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(SpName)
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group delete --name $(resourceGroup) --no-wait --yes --subscription $(subscriptionName)
  displayName: 'Delete resource group'